# Generated by Django 3.2.9 on 2021-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211020_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
