# Generated by Django 3.2.9 on 2021-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(default='', max_length=24, null=True),
        ),
    ]
